### PR TITLE
file_list_modified callback changed in karma 0.13

### PR DESCRIPTION
**Pull request by hikirsch**
in karma 0.13, they removed the filesPromise and replaced it with the real files object. this pull request fixes that.

### CODE REVIEW

**Comment by hikirsch** [comment]
Fixes: https://github.com/karma-runner/karma-closure/issues/23

**Comment by zzo** [comment]
what's up with the travis failures?  something about firefox not being available?

**Comment by hikirsch** [comment]
i don't know. there's no mention of firefox anywhere in the project. is there a way to test travis without having to push to the repo?

**Comment by zzo** [comment]
yes there is a little 'reload' icon in the upper right corner or the results which I just clicked to re-run it.
Looks like the issue is after running 'grunt test' the .travis.yml file then runs:

    ./node_modules/karma/bin/karma start test-app/karma.conf.js --browsers Firefox --single-run --reporters dots

but the karma-firefox-launcher plugin is never installed so karma barfs.
Maybe just adding

    npm install karma-firefox-launcher

to .travis.yml in before_script block will fix it?  Do you mind adding that to your PR and giving it another shot?

thanks!!
   Mark

PS And yes I have no idea how this ever worked :)

**Comment by hikirsch** [comment]
looks like that fixed it.

**Comment by zzo** [comment]
great thanks!!
karma-closure 0.1.1 on npm
  Mark

On Fri, Sep 11, 2015 at 1:46 PM, Adam S. Kirschner <notifications@github.com

**Pull request merged**
